### ISSUE TITLE
Docs conflict regarding Python 2 support

### ISSUE THREAD

**Issue by stevepiercy** [websauna/pyramid_sms#1]
See also that Python 2.6 support has been dropped in Pyramid 1.7 http://docs.pylonsproject.org/projects/pyramid/en/1.7-branch/whatsnew-1.7.html#backwards-incompatibilities

Affected files include:
- https://github.com/websauna/pyramid_sms/blob/master/CONTRIBUTING.rst
- https://github.com/websauna/pyramid_sms/blob/master/docs/installation.rst

**Comment by miohtama** [comment]
Fixed. Was due to https://github.com/audreyr/cookiecutter-pypackage default text.
